from typing import Callable, NamedTuple
from compiler import Compiler, SeaFunction, SeaRecord, SeaType

class TypeDescriptor(NamedTuple):
	pointers: int # Amount of pointers
	name: str
	arrays: int # Amount of arrays

class Backend:
	def __init__(self, compiler: Compiler, output_file: str):
		self.compiler = compiler
		self.output_file = output_file
		self.line_ending = '\n'

	def __enter__(self):
		self.file = open(self.output_file, 'w')
		return self.file

	def __exit__(self):
		self.file.close()

	def write(self, text: str):
		self.file.write(text)

	def writeln(self, text: str):
		self.file.write(text)
		self.file.write('\n')

	def type(self, type: SeaType) -> str: ...

	def use(self, module: str): ...
	def rec(self, name: str, record: SeaRecord): ...
	def fun(self, name: str, func: SeaFunction): ...
	def var(self, name: str, type: SeaType, value: Callable): ...
	def let(self, name: str, type: SeaType, value: Callable): ...
	def ret(self, value: Callable): ...

	def block_start(self): ...
	def block_end(self): ...
	def invoke(self, it: str, args: str): ...
	def if_(self, cond: str): ...
	def else_(self): ...
	def for_(self, define: str, cond: str, inc: str): ...
	def each(self, var: str, of: str): ...

	def true(self): ...
	def false(self): ...

	def dot(self, left: Callable, right: Callable): ...
	def not_(self, value: Callable): ...
	def and_(self, left: Callable, right: Callable): ...
	def or_(self, left: Callable, right: Callable): ...
	def eq(self, left: Callable, right: Callable): ...
	def neq(self, left: Callable, right: Callable): ...
	def gt(self, left: Callable, right: Callable): ...
	def gteq(self, left: Callable, right: Callable): ...
	def lt(self, left: Callable, right: Callable): ...
	def lteq(self, left: Callable, right: Callable): ...
	def inc(self, value: Callable): ...
	def dec(self, value: Callable): ...

	def add(self, left: Callable, right: Callable): ...
	def sub(self, left: Callable, right: Callable): ...
	def mul(self, left: Callable, right: Callable): ...
	def div(self, left: Callable, right: Callable): ...
	def mod(self, left: Callable, right: Callable): ...

	def number(self, it: str): ...
	def id(self, it: str): ...
	def string(self, it: str): ...

	def raw(self, code: Callable): ...
